### ISSUE TITLE
GeoJSON → TopoJSON conversion issues

### ISSUE THREAD

**Issue by matiaskorhonen** [topojson/topojson#163]
I'm having some issues converting GeoJSON to TopoJSON, specifically with the data for Russia from the Natural Earth data set.

Basically I want to convert this GeoJSON to TopoJSON:

![rus geojson 2014-04-16 10-41-26 2014-04-16 10-41-28](https://cloud.githubusercontent.com/assets/43314/2717153/84fc66d8-c53a-11e3-9146-430120038049.png)

The problem is that the TopoJSON output ends up corrupted:

![rus geojson 2014-04-16 10-41-45 2014-04-16 10-41-48](https://cloud.githubusercontent.com/assets/43314/2717155/90c395fe-c53a-11e3-96b2-3eafaa2f7622.png)

I'm using TopoJSON v1.6.8 and these command line options:

``` sh
topojson --id-property ADM0_A3 --properties --out RUS.topojson RUS.geojson
```

The GeoJSON and TopoJSON files can be found here: https://gist.github.com/matiaskorhonen/365290a9134d0b798f25

**Comment by meule** [comment]
Thank you!
