### ISSUE TITLE
Full library in browser

### ISSUE THREAD

**Issue by astjohn** [topojson/topojson#208]
Thanks for the great library! I would love to be able to convert geoJSON objects into topoJSON on the client before sending to the server. Are there any plans to create a full library for client side? I have attempted to address by experimenting with Browserify, but unfortunately, it isn't working out so well yet.

Having the conversion client side would eliminate the requirement of introducing node on our servers.

**Comment by tmcw** [comment]
:+1: here: I'm using TopoJSON in geojson.io, and am pinning to 1.6.8 because of the server/browser switch in 1.6.11. Trying something like `require("topojson/index.js")` as a workaround seems to confuse browserify.

**Comment by JulianMayorga** [comment]
:+1:! I would also like to be able to convert GeoJSON to TopoJSON client-side.

**Comment by dickthestick** [comment]
Does anyone have a workaround for this? I've been banging my head against the desk with trying to browserify the server API. Did try using the wonderful http://topojsonify.herokuapp.com/ POST API, but my data beyond its set size limits and I don't have enough talent to be able to reverse engineer/copy it.

**Comment by jczaplew** [comment]
:+1:. This would be very useful to have.

**Comment by korczis** [comment]
Any updates?

**Comment by jczaplew** [comment]
Here is an example of how to repackage topojson so that both the client and server api are available clientside - https://github.com/jczaplew/topojson-everywhere

**Comment by mbostock** [comment]
This is now in master and will be released as 2.0 in the near future.
