### ISSUE TITLE
"--invert false" setting doesn't work

### ISSUE THREAD

**Issue by rufushuang** [topojson/topojson#209]
Is it caused by the 'optimist' doesn't support 'auto' on 'boolean' type?

``` javascript
    .options("invert", {
      describe: "in conjunction with --width or --height, whether to invert y",
      type: "boolean",
      default: "auto"
    })
```

when '--invert false' is set, the argv.invert changes to be an array insteadof a string

``` javascript
argv.invert == ['auto', false];
```

This can be reviewed as following code change to bin\topojson

``` javascript
      console.log("1:"); console.log(argv.invert);
      if (argv.invert.length !== undefined) argv.invert = argv.invert[argv.invert.length - 1]
      console.log("2:"); console.log(argv.invert);
      if (argv.invert === "auto") argv.invert = !argv.projection;
      console.log("3:"); console.log(argv.invert);
```

Add argv.invert = argv.invert[argv.invert.length - 1] can fix the 'true'/'false' setting, but it makes 'auto' setting useless.

**Comment by mbostock** [comment]
The --invert functionality is moving to [d3-geo-projection’s geoscale](https://github.com/d3/d3-geo-projection/issues/77) in 2.0, and I’ll be using [commander](https://github.com/tj/commander.js) instead of optimist.
