### ISSUE TITLE
Merge polygons from command line

### ISSUE THREAD

**Issue by stevenmanton** [topojson/topojson#239]
I absolutely love this tool and the work you guys have done and I feel bad adding an issue without first attempting a pull request. One thing I'd love to see in the command line tool is the ability to merge polygons based on the id. For instance, this is useful in downsampling zip5 to zip4 (zip3 seems to be easy to find online). I imagine this would be simple using `topojson.mergeArcs`, but I'm not sure the best way to do so. Thanks again you guys for the awesome tool!

**Comment by mbostock** [comment]
I think this should be covered by topomerge; see topojson/topojson-client#3.
