### ISSUE TITLE
polygon ID:356 India

### ISSUE THREAD

**Issue by sivakumaranr** [topojson/topojson#243]
Hi Team,

I just realized that Indian polygon is not appropriate. can you please fix it?
Please find attached image for you reference
Regards,
Sivakumaran
![india](https://cloud.githubusercontent.com/assets/12729015/7958035/56a82d66-0a09-11e5-8938-5cdc60b2144c.png)

**Comment by mbostock** [comment]
Note sure what this issue was referring to. Perhaps the example world-110m.json and world-50m.json files? These come from [world-atlas](https://github.com/topojson/world-atlas) and then from [Natural Earth](http://www.naturalearthdata.com/), so any problem would need to be fixed in Natural Earth.
