### ISSUE TITLE
Properties beginning with numbers or containing slashes are not being retained properly.

### ISSUE THREAD

**Issue by technicolorenvy** [topojson/topojson#250]
This may be documented somewhere that I've missed, if so my apologies.

I'm attempting to create a TopoJSON file from a GeoJSON file and add external properties from a CSV. The external properties in the CSV are years formatted in mm/dd/yy format. The topojson command I'm running looks as follows

```
topojson \
-o usStates5mTopo.json \
-e test.csv \
--id-property State,NAME \
--properties state=State,state=NAME,12/31/99 \
-- \
usStates5m.json
```

I do end up with '12/31/99' properties in my 'properties' object for each entry in the resulting 'usStates5mTopo.json' file, but the value is not the value from the csv, it appears to be some kind of conversion of the year '12/31/99' to the float 0.0039100684261974585. Further experimentation shows that props such as 2014 will be converted as well to 0.027649769585253454 or 01 to 1 and so on. It would appear that props beginning with a number is unsupported, but the docs don't seem to indicate this fact.

Similarly, I am also seeing issues with props that contain slashes such as 'foo/bar' not being found and therefore not being attached to the properties object for each entry in the resulting topojson file.

If there is a workaround for proper retention of props beginning with numbers or containing slashes, it would be good to know, but this is easy enough to workaround. I did note the docs contain the following note `(Note: it is not currently possible to preserve properties whose name contains a comma, leading plus or equals sign.)`, but doesn't seem to include any notes pertaining the above use-cases I ran into.

**Comment by mbostock** [comment]
Yeah, the whole design of `--properties` needs an overhaul. It’s trying to do too much with a concise syntax. I also think it’d be useful to break out joining, mapping and filtering properties to a separate executable so that you can perform these operations independent of converting to TopoJSON. This should probably happen as a 2.0 release, but I’m deep into the D3 4.0 release at the moment and so I can’t look at this right now. Sorry.

**Comment by mbostock** [comment]
This feature is going away in 2.0, to be replaced with [ndjson-cli](https://github.com/mbostock/ndjson-cli).
