### ISSUE TITLE
presimplify breaking paths

### ISSUE THREAD

**Issue by mattosborn** [topojson/topojson#251]
I'm using topojson.presimplify and the following code:

```
this.simplify = d3.geo.transform({
  point: function(x, y, z) {
    if (z >= area) this.stream.point(x,y);
  }
})
```

After a certain `area` cutoff, or if I remove this simplify filter entirely, my map goes from looking like this:
![screenshot from 2015-06-15 14 42 29](https://cloud.githubusercontent.com/assets/960919/8161274/c14f087a-136d-11e5-8d48-0f90af3ec381.png)

to looking like this...
![screenshot from 2015-06-15 14 41 45](https://cloud.githubusercontent.com/assets/960919/8161273/bb6669a8-136d-11e5-9ffe-ac0da52a23ba.png)

It looks like the culprit is a broken path for one of the countries. In the working version all of the points in the rendered path lie in the region of 120-150 and 340-370. In the broken version there are a handful of points lying quite far outside that region:

```
L6.735679788899688,288.07037581228843L2.8229243136240143,276.9563006498307L-1,260.54439523878006L-1,204.45560476121992L-1,204.45560476121992L2.8229243136240143,188.04369935016928L6.735679788899688,176.9296241877116
```

Any idea what the reason for this could be?

**Comment by mbostock** [comment]
Typically this is a winding order problem, where a polygon’s winding order becomes inverted after simplification.

**Comment by mattosborn** [comment]
How hard is this to fix? Anything I can do to help?

Any ideas on a possible workaround in the mean time?

**Comment by mbostock** [comment]
This is an extremely difficult issue to fix in general, but it might be easier to fix in this specific case… I’m not sure. Are you building your own TopoJSON or are you using one of the supplied examples?

**Comment by sttawm** [comment]
Interesting problem. I'm not sure what the solution might be either, but here are a few thoughts:
* try using a transparent fill to identify the country causing the issue (if it's a winding-order issue, I'd guess that it's a small country and that there's a small white spec somewhere in the shape of the offending country. But if it's a large country causing the issue, transparency should make it obvious)
* If it's a winding order issue as Mike suggests, it seems possible that filtering small polygons would help.
* ensure that the areas of the endpoints are in fact infinity (I think it's unlikely that they are not, but who knows)
* If the input is valid, an [algorithm](https://www.jasondavies.com/simplify/) that avoids introducing self-intersections might help (assuming self-intersections are messing with the winding-order)

I also wonder what operations are performed between coordinate-filtering and rendering. For instance, the [standard projection stream](#https://github.com/mbostock/d3/wiki/Geo-Projections#stream) involves clipping and projection, etc.

**Comment by mattosborn** [comment]
We're using Natural Earth data to build our own TopoJSON.

The country with the broken path is Ukraine. If I give it a partially-transparent, blue fill and a red stroke it looks like this:
![screenshot from 2015-06-16 10 55 30](https://cloud.githubusercontent.com/assets/960919/8180502/388c8126-1416-11e5-9953-0e7a24ad8ba1.png)

If I change the `fill-rule` to `evenodd` it removes the fill from the country itself:
![screenshot from 2015-06-16 10 51 06](https://cloud.githubusercontent.com/assets/960919/8180477/08e8a026-1416-11e5-865f-63f5237140a3.png)

So it looks like you're right in thinking this is a winding order issue caused by a self-intersection.

The thing I'm confused about is why this only happens at low or no simplification. I thought `presimplify` just performed annotation. Should it be changing the paths without the render-time simplification step?

**Comment by mbostock** [comment]
Not sure if there’s anything I can do with this issue. It’s possible for simplification to introduce winding order problems, but normally [topojson.filter](https://github.com/topojson/topojson-simplify/blob/master/README.md#filter) takes care of removing those small polygons so they can’t cause a winding order inversion. However, if you’re following my [dynamic simplification example](https://bl.ocks.org/mbostock/6245977), it’s just filtering the points and not filtering the rings, which probably makes this problem much more likely. You’d need to do some more work to dynamically filtering the rings, too. Although often it makes more sense to use projected planar geometry in conjunction with dynamic simplification, and then you don’t have to worry about winding order inversion, either.
