### ISSUE TITLE
Feature request/inquiry: Merging/diffing separate topojson features

### ISSUE THREAD

**Issue by mmase** [topojson/topojson#252]
Apologies if this is out of scope of what belongs here. I more or less would like to know, is this possible?

I was wondering if there was a way, on the client, to do a merge from two (or more) topojson features (separate files, separate json calls). In particular, is there a way to combine topography and then create shapes based on the diff?

I've attached an example to illustrate this. In this case, `map_a` has a feature with some property of 1 and `map_b` has a feature with a property of 2. I'm wondering is it possible to merge these (on the client) and then create new features where they intersect and append properties when necessary or desired (in this case I'm simply adding the properties so that the new feature has a property with a value of 3).

![topojson-merge](https://cloud.githubusercontent.com/assets/753529/8174474/f6103592-13aa-11e5-972d-ff7ab717e9f9.gif)

**Comment by mbostock** [comment]
You want something like [Java Topology Suite (JTS)](https://en.wikipedia.org/wiki/JTS_Topology_Suite) for this. [Turf](http://turfjs.org/) is a port of JTS (a wrapper on [JSTS](https://github.com/bjornharrtell/jsts)) that will work in the browser.

http://turfjs.org/docs/#difference
http://turfjs.org/docs/#intersect
