### ISSUE TITLE
Pre-projection causes some inner polygon rings to disappear. 

### ISSUE THREAD

**Issue by mmase** [topojson/topojson#256]
For some reason, when preprojecting topology with `--projection='d3.geo.mercator().center([-97.375,35.125]).translate([0,0])'`, for example, some inner rings fill/disappear. I don't seem to recognize a pattern, but when the topology is not preprojected, the rings are always maintained. And it seems to be one or two features at most. Not all of them. Any ideas?

**Comment by masedesign** [comment]
Turns out this was solved with quantiziation. Really weird that quantiziation + projection can cause weird results. I guess this isn't a bug? But I'd love to hear thoughts on what might cause this.

**Comment by mbostock** [comment]
If you’re using quantization, it’s possible the rings are getting collapsed into coincident points after projecting, and then getting removed. 🤔
