### ISSUE TITLE
empy arc identifier in feature's arc list

### ISSUE THREAD

**Issue by hpfast** [topojson/topojson#258]
I'm getting empty arcs in geometry definitions (so not in the arcs element, but in the array of arc ids for a feature).

I'm investigating whether anything in my input data is causing this. Docs and issues I've been able to find talk about input data problems and missing or empty arcs in the actual arcs array, but I couldn't find anything about what causes it in the identifiers array on a feature. So I wanted to ask, is there any known cause for this? See highlighted below:

```
{
    "type": "Topology",
        "objects": {
            "countries": {
                "type": "GeometryCollection",
                "geometries": [
                {
                    "type": "MultiPolygon",
                    "properties": {
                        "id": "1586",
                        ...
                    },
                    "arcs": [
                        [
                        [
                        0
                        ]
                        ],
                    [
                        [
                        1
                        ]
                    ],
                    [
                        [
                        2
                        ]
                    ],
>>>>            [],          <<<<
                    [
                        [
                        3
                        ]
                    ],
                    [
                        [
                        4
                        ]
                    ],
                    [
                        [
                        5
                        ]
                    ]
                    ]
               }
                ]
            }
        },
        "arcs": [
```

**Comment by hpfast** [comment]
ok, it looks like my affected geometries cross 180 degrees, so maybe the issues relating to the arcs array are relevant for this too.

**Comment by mbostock** [comment]
Hard to say without seeing the input data, and without knowing if you’re using pre-quantization, simplification, filtering, etc. There are ways that coincident points get collapsed, leading to arc removal, but I’m not sure exactly what is going on here and whether or not that is the expected behavior.
