### ISSUE TITLE
Hard to get working on Ubuntu 14.04

### ISSUE THREAD

**Issue by markjd84** [topojson/topojson#262]
Thought I'd try to install as looks like a great tool. Used the `npm install` route per the wiki. Unfortunately, whilst npm reports having installed successfully, nothing happens _at all_ when invoking the command-line tool:

```
$ topojson -o topo.json geo.json
$ 
$ ls
.  ..  geo.json
$
```

Had done a fair amount of googling around and tried reinstalling node, npm, and loads of libraries, but to no avail. Then I found [this](http://stackoverflow.com/questions/16628638/how-to-run-topojson). It is not the first answer but the second that worked for me: basically ubuntu already has a `node` command for something or other, and it stops the topojson CLI working. As a result one of the scripts needs editing to access `nodejs`.

I know it's really Ubuntu's problem, not Topojson's, but could we add something to the install docs? Seems like it might come up for others.

**Comment by mbostock** [comment]
Seems like an issue for anyone that wants to run Node scripts on Ubuntu… They’ll need to do something like

```
sudo ln -s "$(which nodejs)" /usr/bin/node 
```
