### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by mbostock** [topojson/topojson#271]
The `topojson` command currently does quite a few things:
- It reprojects geometry.
- It converts geometries to topologies.
- It quantizes topologies.
- It filters and transforms properties.
- It computes new properties by joining to external data.

I probably forgot some things. It’d be nice to make this more UNIX-y by breaking the `topojson` command up into several smaller commands.

For example, maybe the `topojson` command only computes a non-quantized topology from a given set of geometry inputs, and always passes through any defined properties on those inputs.

If you want to quantize or change the defined properties, you’d pass the output of `topojson` to separate commands, say, `topojson-quantize` or `topojson-data`. (The `topojson-data` command might also work with GeoJSON…)

If you want to reproject the geometry, maybe you’d run it through `topojson-reproject` tool after running it through `topojson`, but before `topojson-quantize`. (Or maybe you’d run it through `geojson-reproject` or `ogr2ogr` before passing it to `topojson`?)

**Comment by rogerfischer** [comment]
Hey Mike, 
I have several things I would love to discuss with you about TopoJSON. E.g. adding a new id property for merged objects, TopoJSON editing tools etc. Let me know if you have time for this.

**Comment by mbostock** [comment]
For `topojson` 2.0, the new implementation will be written as modules using [Rollup](http://rollupjs.org) to transpile bundles for Node.js and in-browser GeoJSON-to-TopoJSON conversion.

The new implementation will be strictly incremental: you can construct an empty *topology* and then add GeoJSON objects to that topology. If the new object has coincident points with old objects, this may cut existing arcs in the topology, changing the definition of old objects. During construction, coordinates from input objects will be copied into a Float64Array that alternates between *x* and *y* coordinates (XY packing; akin to RGBA for image buffers). This array will be repeatedly doubled to accommodate new data after de-duplication.

The `topojson -n` command should take newline-delimited JSON, a stream of GeoJSON objects, as input. Without `-n`, it would be nice to use a streaming JSON parser that can pull out the features from a top-level feature collection (or geometries from a top-level geometry collection); [JSONStream](https://github.com/dominictarr/JSONStream) looks like it would work for Node but I’d need to rewrite this on top of WhatWG readable streams (as in [mbostock/shapefile](https://github.com/mbostock/shapefile/blob/master/index.js)) to get this to work cross-platform, so it’s probably simplest to start with a cross-platform implementation that expects already-parsed objects as inputs.

We *may* want a pre-quantization step, in which case the coordinates would be represented as an Int32Array. I’m not sure yet whether than pre-quantization should happen as a pre-processing step on the GeoJSON input to `topojson`; probably not because there’s no concept of quantized GeoJSON, and because the `topojson` tool will need to know whether the input coordinates are integers or floats.

So:

* No shapefile parsing. Pipe from [shp2json](https://github.com/mbostock/shapefile/blob/master/README.md#shp2json) instead.
* No simplification. Pipe to a forthcoming topojson-simplify command.
* No post-quantization. Pipe to a forthcoming topojson-quantize command?
* No property remapping. Use [ndjson-map](https://github.com/mbostock/ndjson-cli/blob/master/README.md#ndjson_map) *etc.*
* No external property joining. Use [ndjson-join](https://github.com/mbostock/ndjson-cli/blob/master/README.md#ndjson_join) *etc.*
* No CSV or TSV input. Pipe from [dsv2json](https://github.com/d3/d3-dsv/blob/master/README.md#dsv2json).

TBD:

* Pole stitching? Needs to happen prior to topology construction.
* Winding order forcing? Needs to happen prior to topology construction.
* Reprojection? Needs to happen prior to topology construction.

Probably the above commands should happen in a `geojson-project` tool that takes WGS84 GeoJSON input and produces spherical or projected GeoJSON output, and you’d then pipe that to `topojson`. This will require resurrecting [d3.geo.project](https://github.com/d3/d3-geo-projection/blob/v0.2.16/src/project.js) as [d3.geoProject](https://github.com/d3/d3-geo-projection/issues/64). There’s also the issue that D3 treats GeoJSON as having *spherical coordinates*, and line segments being great arcs rather than straight lines in whatever coordinate system is being used; this is necessary for how D3 implements arbitrary projection aspects. (See [antimeridian cutting](https://bl.ocks.org/mbostock/3788999).) But I *think* topology construction can be done completely agnostic to the coordinate system, and even whether that coordinate system is planar or spherical.

Actually, that suggests an equivalently-valid approach would be to do the projection *after* converting to TopoJSON as a `topojson-project` command, which has the added bonus in that it can operate directly on the topology’s arcs and ignore the objects entirely. Although you’d have to be careful because stitching and clipping could remove and affect arcs in weird ways.

On the other hand, `geojson-project` has the advantage that objects can be streamed and projected individually, whereas projected TopoJSON requires reading the entire topology.

**Comment by mbostock** [comment]
> But I think topology construction can be done completely agnostic to the coordinate system, and even whether that coordinate system is planar or spherical.

Unfortunately that’s not true because pole stitching changes the topology. But assuming you have spherical GeoJSON as input, you can project after constructing the topology.

**Comment by mbostock** [comment]
This is merged to master and almost done, #294 and #295 notwithstanding.
