### ISSUE TITLE
Merging not working as expected.

### ISSUE THREAD

**Issue by rickj33** [topojson/topojson#289]
I am trying to merge a collection of zipcodes into a single feature, but the resulting feature has an area which seems to be excluded (ie a hole).

The following images were generated using the same topojson file, the first one shows the area which should be merged. 
## Features to merge

![individualfeatures](https://cloud.githubusercontent.com/assets/154450/19130584/58f84cec-8b11-11e6-9f4f-8abf774f6200.jpg)
## Result of merging

![mergedfeatureswithcomment](https://cloud.githubusercontent.com/assets/154450/19130576/516f090c-8b11-11e6-945b-59c9fcffbe1b.jpg)
## Overlay the merged features with non merged features, showing gap.

![combinedimage](https://cloud.githubusercontent.com/assets/154450/19130586/5e8a7162-8b11-11e6-9042-79934992c403.jpg)
## Demo

I created a bl.ock which demonstrates the problem,  [TopoJsonMergeIssue](https://bl.ocks.org/rickj33/6d2ae74b0f4ac9d15b899032e840d3e8), it is using the same topojson file as the images above.

I used ogr2ogr to extract the zipcodes, from a shapefile, to use and output it as a GeoJson, then used topjson to convert the GeoJson.

The command line settings i used to extract the topojson used in the blocks is

> topojson --id-property=ZIP  --filter=none  --no-pre-quantization --post-quantization=1e4 --simplify-proportion=.8 --bbox -o  E:\code\Research\MergeTopoFeatures\midAtlantic.topojson E:\code\Research\MergeTopoFeatures\midAtlantic.geojson 

One thing I did notice was if I used a smaller set of zipcodes then the merging would work correctly.
## Smaller set of Zipcodes

![smallerboundingbox](https://cloud.githubusercontent.com/assets/154450/19131101/ac8fc6e4-8b13-11e6-8b72-778c570b6489.jpg)

Here is the [topojson](https://gist.githubusercontent.com/rickj33/6d2ae74b0f4ac9d15b899032e840d3e8/raw/ab2b40a21c7ae30c43999d9fde834972cc4f5070/midAtlanticDc.json)  used for the smaller set of zipcodes.

**Comment by chris1313n** [comment]
can you push this code to test, so i can play with it?

**Comment by mbostock** [comment]
I suspect this has something to do with post-quantization that is causing the topology to be ambiguous, like having multiple degenerate (zero-area) rings at the same point. You might want to try merging on a non-quantized topology instead. (And if you wanted, you could then convert the merged topology back to GeoJSON, and then convert to a new quantized, merged TopoJSON topology. This’ll be a little bit easier in 2.0 with the new [topoquantize tool](https://github.com/topojson/topojson-simplify/issues/1).) Sorry if this isn’t helpful…
