### ISSUE TITLE
which topojson blank

### ISSUE THREAD

**Issue by eriksays** [topojson/topojson#297]
This may not be the correct place for this; if so, I apologize.

I'm attempting to install topojson and am unable to see it on my path

```
$ npm install -g topojson
/usr/local/bin/geo2topo -> /usr/local/lib/node_modules/topojson/bin/geo2topo
/usr/local/lib
└─┬ topojson@2.0.0 
  └─┬ commander@2.9.0 
    └── graceful-readlink@1.0.1 

$ which topojson
$ 

$ which geo2topo
/usr/local/bin/geo2topo

```

I have also confirmed /usr/local/bin is in my path.

Thanks

**Comment by mbostock** [comment]
Per the [release notes](https://github.com/topojson/topojson/releases/tag/v2.0.0):

> * Extracted [topojson-client](https://github.com/topojson/topojson-client) and [topojson-simplify](https://github.com/topojson/topojson-simplify) modules!
> * The monolithic topojson command-line tool is dead! Long live [geo2topo](https://github.com/topojson/topojson/blob/master/README.md#geo2topo)!
> * Simplified the [topojson.topology](https://github.com/topojson/topojson#topology) API.
> * Now available [in-browser](https://github.com/topojson/topojson/blob/master/README.md#installing)!

So, if you want to generate TopoJSON, you’ll want to use [geo2topo](https://github.com/topojson/topojson#geo2topo) as of version 2.0. Alternatively, you can `npm install -g topojson@1` to continue using the old version. However, I highly recommend upgrading! See the new [California Population Density](https://bl.ocks.org/mbostock/5562380) map as an example.
