### ISSUE TITLE
geo2topo syntax when using stdin and omitting the object name

### ISSUE THREAD

**Issue by bmweiner** [topojson/topojson#301]
I would like to assign a name ("states") to the object created by geo2topo when using stdin ("-") as an input. For example, without any args:

    shp2json cb_2015_us_state_20m.shp | geo2topo -q 1e5 | toposimplify -p 1 -f > us.json

assigns the default name "-" as expected. I thought the following may work:

    shp2json cb_2015_us_state_20m.shp | geo2topo states="-" -q 1e5 | toposimplify -p 1 -f > us.json

but it still assigns "-". I started to look through your source, but wasn't able to figure it out... Is there a way to do this with the CLI or would this be an enhancement? Thanks!

**Comment by bmweiner** [comment]
Please disregard, `shp2json cb_2015_us_state_20m.shp | geo2topo states="-" -q 1e5 | toposimplify -p 1 -f > us.json` did what i wanted.

**Comment by mbostock** [comment]
As you determined, this works:

```bash
shp2json cb_2015_us_state_20m.shp | geo2topo states=-
```

This also works, and is nice if you have multiple inputs:

```bash
geo2topo states=<(shp2json cb_2015_us_state_20m.shp)
```

**Comment by bmweiner** [comment]
Nice, thanks!
