### ISSUE TITLE
v1 to v2 Migration Issues (pole stitching and property preservation)

### ISSUE THREAD

**Issue by vicchi** [topojson/topojson#302]
We're currently using the last v1 release (v1.6.27) of the `topojson` command line tool as follows:

`$ topojson -q 65536 --no-stitch-poles -p iso_a2 -o foo.topojson foo.geojson`

In trying to to migrate to the new v2 command line tools, it looks like _some_ of the above can be achieved along the lines of the following:

`$ geo2topo foo.geojson | topoquantize 65536 > foo.topojson`

However ... the v2 documentation seems to imply that as the stitching functionality has now moved to the D3 `geostitch` command, the new `geo2topo` command implicitly performs the equivalent of _never_ pole stitching, and if you want pole stitching (which we don't) you'd need to use `geostitch`. Can someone confirm this?

But ... it looks like the property preservation functionality never got implemented in v2. The v2 checklist in https://github.com/topojson/topojson/pull/291 mentions this but it's not checked as implemented. Some reasonably in depth reading of the v2 documentation doesn't mention this either. Did this get implemented and I can't find the right reference in the documentation (a distinct possibility) or did this get dropped in v2?

**Comment by mbostock** [comment]
Yes, you must use `geostitch` to stitch antimeridian cuts (or more precisely, turn equirectangular WGS84 coordinates into spherical coordinates).

Properties are preserved by default. If you want to filter, join or transform properties, I recommend using ndjson-cli as described in my tutorial, Command-Line Cartography.

**Comment by mbostock** [comment]
https://medium.com/@mbostock/command-line-cartography-part-1-897aa8f8ca2c

**Comment by vicchi** [comment]
Thanks Mike. Fabulously quick response. It's good to see my reading of the documentation for pole stitching was correct.

On the topic of properties, am I right in assuming that if we want to filter out _all_ properties and retain one or more specific properties, we'd therefore need to also convert the GeoJSON source into ND JSON as an intermediate step in the command pipeline? I can see how to delete a specific property using `ndjson-filter` but can't see how to delete _all_ of them and specify which ones to preserve (I appreciate this may be out of the scope of this issue slightly but hopefully it's applicable for people who are having similar fun and games in migrating!) ... ?

**Comment by mbostock** [comment]
If the JSON is formatted without newlines (as is the case with [shapefile](https://github.com/mbostock/shapefile)’s [shp2json](https://github.com/mbostock/shapefile/blob/master/README.md#shp2json), but you didn’t specify how your foo.geojson was created), then it’s *de facto* newline-delimited JSON as well, it’s just that there’s only a single object of the FeatureCollection rather than a stream of Feature objects. So in that case, you could use the following command to strip the feature properties:

```
ndjson-map '(d.features.forEach(d => delete d.properties), d)' < in.geojson > out.geojson
```

If you want to process the features individually, then you use ndjson-split to break out the features (or equivalently shp2json -n) and ndjson-reduce to put them back together again:

```
ndjson-split 'd.features' < in.geojson \
  | ndjson-map '(delete d.properties, d)' \
  | ndjson-reduce 'p.features.push(d), p' '{type: "FeatureCollection", features: []}' \
  > out.geojson
```

**Comment by vicchi** [comment]
Thanks - I'll give that a try. We've been using `ogr2ogr2` to transform from shapefile to GeoJSON, but I'll look at `ndjson-split` first and then, if that doesn't work, I'll switch from `ogr2ogr` to `shp2json`.

**Comment by mbostock** [comment]
You can use ndjson-cat to remove the newlines from ogr2ogr’s output. But… I recommend using shapefile’s shp2json instead. 😁

**Comment by vicchi** [comment]
One final thing. I can see in your examples how to delete _all_ properties, but I'm not yet clear on how to preserve a specific property or list of specific properties? For example, in the original `topojson` command we were deleting all properties except the `iso_a2` property?

**Comment by vicchi** [comment]
Something like `'["ISO_A2"].includes(d.properties)'` perhaps?

**Comment by mbostock** [comment]
ndjson-map takes a JavaScript expression, so ask yourself, how would I take an object *d* like this:

```json
{
  "foo": 1,
  "bar": 2,
  "baz": 3,
  "qux": 4
}
```

And derive an object like this:

```json
{
  "foo": 1
}
```

You could iterate over the keys using Object.keys and then delete, but probably better is to construct a new object containing just the fields you want:

```
ndjson-split 'd.features' < in.geojson \
  | ndjson-map 'd.properties = {ISO_A2: d.properties.ISO_A2}, d' \
  | ndjson-reduce \
  | ndjson-map '{type: "FeatureCollection", features: d}' \
  > out.geojson```

**Comment by vicchi** [comment]
#facepalm Of course! Thank you. I'll leave it there and go and implement this. Thank Mike and have a great weekend.
