### ISSUE TITLE
topo2geo produces wrongly oriented polygons

### ISSUE THREAD

**Issue by tyrasd** [topojson/topojson#303]
The result of a topojson to geojson (topo2geo) conversion produces polygons with a wrong winding order:

    $ wget https://d3js.org/world-110m.v1.json
    $ topo2geo countries=countries.json < world-110m.v1.json
    $ geojsonhint countries.json 
      1:1  warning  Polygons and MultiPolygons should follow the right-hand rule
    ⚠ 177 warnings

(this ticket follows https://github.com/d3/d3-geo/pull/79#issuecomment-280862551)

**Comment by mbostock** [comment]
topo2geo doesn’t change the winding order of polygons, so this simply means that the input topology is already in the wrong winding order. You should test this against the latest [world-atlas](https://github.com/topojson/world-atlas) input (and for that matter, the Natural Earth shapefiles from which world-atlas is generated).

**Comment by mbloch** [comment]
The recent update to the GeoJSON spec ([RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.1.6)) requires the opposite winding order to the Shapefile spec, so GeoJSON files that originated as Shapefiles, then were converted to TopoJSON and finally to GeoJSON via `topo2geo` will have the "wrong" winding order, according to RFC 7946 and `geojsonhint`.

**Comment by tyrasd** [comment]
@mbostock this issue also happens with the input generated by topojson/world-atlas (I've updated this in the ticket description above)

**Comment by mbostock** [comment]
Folding into d3/d3-geo#79.
