### ISSUE TITLE
Add this library to jsDelivr

### ISSUE THREAD

**Issue by LaurentGoderre** [topojson/topojson#306]
If it was added to jsDelivr, we could get a request to get D3 and topojson in one single request.

**Comment by mbostock** [comment]
I recommend using jsDelivr (or similarly unpkg) through npm:

https://cdn.jsdelivr.net/npm/topojson/

**Comment by LaurentGoderre** [comment]
For posterity, here's how to get d3 and topojson in one call `https://cdn.jsdelivr.net/combine/npm/topojson@3.0.0,npm/d3@4.7.4`
