### ISSUE TITLE
Indiemaps link dead domain seems to be expired

### ISSUE THREAD

**Issue by phocks** [topojson/topojson#308]
Just letting you know the link http://indiemaps.com/blog/2009/02/e00parser-an-actionscript-3-parser-for-the-arcinfo-export-topological-gis-format/ referenced in the README first paragraph Arc/Info Export format, .e00 took me to a survey page and it looks like the domain has expired.

**Comment by mbostock** [comment]
Ick. Thanks for letting me know!
