### ISSUE TITLE
broken link in wiki to topology-test.js

### ISSUE THREAD

**Issue by meetar** [topojson/topojson#317]
On https://github.com/topojson/topojson/wiki/Introduction the link to " topology test suite" (https://github.com/mbostock/topojson/blob/master/test/topology-test.js) is a 404 – looks like it was moved to topojson-server with https://github.com/topojson/topojson/commit/98243ff29e1d3a3621f551fd2e4c48051f6abb0b and https://github.com/topojson/topojson-server/commit/78ca838ee981b739f44eea8f8bde8aeda28313ec ?

**Comment by mbostock** [comment]
Fixed. https://github.com/topojson/topojson-server/blob/v3.0.0/test/topology-test.js
