### ISSUE TITLE
How do I translate and scale when the JSON file is already projected and flattened?

### ISSUE THREAD

**Issue by Hypersapien** [topojson/topojson#330]
I'm trying to use this file https://d3js.org/us-10m.v1.json. I'm pretty sure the data in it is already projected and flattened. If I try to use any kind of projection function with it, the resulting map looks garbled. 

But I still need to translate and scale the map, which is added after the projection function. D3 itself doesn't recognize the translate and scale functions. Is there a projection function that doesn't alter anything? Or is there another way to do it?

**Comment by mbostock** [comment]
Use a transform, most likely d3.geoIdentity: 

https://github.com/d3/d3-geo/blob/master/README.md#transforms
