### ISSUE TITLE
Unable to Zoom in with the [➕] button on Github integration

### ISSUE THREAD

**Issue by Axel-Duval** [topojson/topojson#341]
The topoJSON Github integration in markdown files is not working properly.
I am able to zoom out with the [➖] but I can't to zoom in with the [➕].

Note: he zoom in/out is working well with the mouse scroll.

Reproduction Steps

Paste the following lines in a markdown file:
```sh
{
    "type": "Topology",
    "objects": {
        "collection": {
            "type": "GeometryCollection",
            "geometries": [
                {
                    "id": 1,
                    "type": "Point",
                    "coordinates": [2.3478266686603035, 48.85486458103844],
                    "properties": { "name": "Paris" }
                }
            ]
        }
    }
}
```

**Comment by mbostock** [comment]
I do not maintain GitHub’s TopoJSON integration. You’ll have to talk to them about it.
