### ISSUE TITLE
RuntimeWarning: invalid value encountered in cast   data["bookkeeping_shared_arcs"] = array_bk_sarcs.astype(np.int64).tolist()

### ISSUE THREAD

**Issue by newbie31fr** [topojson/topojson#342]
Console error output 

RuntimeWarning: invalid value encountered in cast
  data["bookkeeping_shared_arcs"] = array_bk_sarcs.astype(np.int64).tolist()

on following python code using topojson apply on vectorized raster from geotiff  (using rasterio and geopandas)

        geoms = list(results)
        gdf = gpd.GeoDataFrame.from_features(geoms)

        # Convertir en topojson et simplifier
        topology = tp.Topology(gdf, prequantize=False)

        topo_simplified = topology.toposimplify(tolerance).to_gdf()

        # Si vous voulez sauvegarder le résultat
        topo_simplified.to_file(output_geopackage, driver="GPKG") 

The output vectorized in geopackage looks good but output console is flooded by error.

**Comment by mbostock** [comment]
You probably want to file the issue here: https://github.com/mattijn/topojson
