### ISSUE TITLE
topojson.topology API call silently alters input data?!

### ISSUE THREAD

**Issue by vsivsi** [topojson/topojson#86]
Hi, I was surprised to discover that the Server side API `topology` call actually overwrites/restructures the passed-in GeoJSON feature collection to TopoJSON in-place.

This was a nasty surprise because the documentation makes no mention (that I can find) of this side-effect of calling `topology`, and because `topology` **_returns**_ the TopoJSON output (which would strongly suggest that it is not altering its input).  

Details: my application is using select subsets of the Features of a pre-built master GeoJSON FeatureCollection to perform geoqueries to a geoindexed MongoDB collection.  The returned results (counting intersecting Points that meet certain criteria) are then added (cached) in the in-memory GeoJSON and the queried subset features are then collected into a new GeoJSON Feature collection and serialized to construct a response to the RESTful API call that initiated the query.

Adding conversion to TopoJSON of the new "response" GeoJSON FeatureCollection (which shares Features with the master FeatureCollection) silently corrupts some of the entries (the query subset) of the master GeoJSON collection as side-effect of calling `topojson.topology`.

In my opinion, a API method that converts one object type to another, and `return`s the "new" object as its output, should not simultaneously alter/destroy the input object in the process.  This would not be the commonly expected behavior, and so is likely to lead to error prone uses of the call.  At a minimum, this behavior should be well documented; but ideally, the default behavior of the`topology` call should be "safe", building-up a new object for its output rather than working in-place within the input datastructure. It is perhaps a good option to have in-place conversion for extremely memory intensive edge cases, but the default behavior should be free of unexpected side-effects on the input(s).  

BTW, TopoJSON is great, thanks for the hard work on it, this is just a rough edge on the API, IMO.  

The following code reproduces the problem for a minimal case:

```
 (function() {
 var geojson_data, topojson, topojson_data;
 topojson = require('topojson');
 geojson_data = {
     "type": "FeatureCollection",
     "crs": {
       "type": "name",
       "properties": {
         "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
       }
     },
     "features": [
       {
         "type": "Feature",
         "geometry": {
           "type": "Polygon",
           "coordinates": [[[12.908659734899926, 52.258453749997294], [12.910137089614084, 52.256896081728044], [12.908659734899926, 52.255338413458794], [12.905705025471613, 52.255338413458794], [12.904227670757455, 52.256896081728044], [12.905705025471613, 52.258453749997294], [12.908659734899926, 52.258453749997294]]]
         },
         "properties": {
           "type": "hexagon",
           "intersects": false
         }
       }, {
         "type": "Feature",
         "geometry": {
           "type": "Polygon",
           "coordinates": [[[12.908659734899926, 52.26156908653579], [12.910137089614084, 52.260011418266544], [12.908659734899926, 52.258453749997294], [12.905705025471613, 52.258453749997294], [12.904227670757455, 52.260011418266544], [12.905705025471613, 52.26156908653579], [12.908659734899926, 52.26156908653579]]]
         },
         "properties": {
           "type": "hexagon",
           "intersects": false
         }
       }
     ]
   };

   console.log("Before:");
   console.log(JSON.stringify(geojson_data.features[0], null, 1));

   topojson_data = topojson.topology({'collection': geojson_data});

   console.log("After:");
   /*
   # The line below fails because topojson.topoology call above actually
   # changed the geojson_data structure in-place rather than creating
   # a new datastructure, so the features array is gone and the index [0] is
   # invalid.
   */
   console.log(JSON.stringify(geojson_data.features[0], null, 1));

 }).call(this);
```

**Comment by mbostock** [comment]
This is now explicitly documented in the API reference; see [topojson.topology](https://github.com/topojson/topojson/blob/master/README.md#topology).

I’d like to rewrite everything to *not* use in-place destructive operations, but that would probably increase the memory overhead on large inputs and make out-of-memory errors more likely. So, I think that should be done in conjunction with converting the input GeoJSON objects into a more efficient representation, say with a single typed array of coordinates using alternating dimensions [*x₀*, *y₀*, *x₁*, *y₁*, …].

And perhaps, we should change TopoJSON to not just use that internally but use that as the serialization format… Though if we do *that*, we should also think about how to make d3-geo more efficient, too, since d3-geo still operates on GeoJSON, not TopoJSON.
